site_name: opciones de privacidad

theme:
  name: material
  language: es
  palette:
    scheme: default


nav:
  - index.md

plugins:
  # - privacy
  - privacy:
      cache: false


extra:
  consent:
    actions:
      - accept
      - manage 
      - reject


copyright: >
  Copyright &copy; 19XX-20XX Autor –
  <a href="#__consent">Cambiar configuración de cookies</a>


extra_javascript:
  - javascripts/consent.js