
services:

  markdown-mkdocs:
    build:  .
    image: mkdocs-local:markdown
    container_name: markdown-mkdocs
    ports:
      - "${PORT:-8000}:8000"
    security_opt: 
      - label=disable
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true


