site_name: demo colores

theme:
  name: material
  language: es


markdown_extensions:
  - markdown-katex:
      no_inline_svg: true
      insert_fonts_css: true
      macro-file: macros.tex


nav:
  - index.md
