site_name: pagetree-plugin

theme:
  name: material
  language: es
  palette:
    scheme: default


plugins:
  - pagetree


nav:
  - index.md
  - nivel 1:
    - opciones/all.md
    - opciones/siblings.md
    - opciones/subtree.md
    - opciones/children.md
    - nivel 2:
      - opciones/subdirectorio/1.md
      - opciones/subdirectorio/2.md
